# Generated by Django 3.0.6 on 2020-06-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
